env: TRAVIS_CI=true
language: c

compiler:
  - gcc
  - clang

services:
  - mysql
  - postgresql

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for mod_sql_mysql
  - sudo apt-get install -y libmysqlclient-dev
  # for mod_sql_postgres
  - sudo apt-get install -y libpq-dev
  # for mod_sql_sqlite
  - sudo apt-get install -y libsqlite3-dev sqlite3
  # for static code analysis
  # for Perl scripts
  - sudo apt-get install -y libdbi-perl libdbd-mysql-perl libdbd-pg-perl libdbd-sqlite3-perl
  - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  # Create the expected database in MySQL
  - mysql -e 'CREATE DATABASE proftpd;' -u root
  # Create the expected database in Postgres
  - psql -c 'CREATE DATABASE proftpd'; -U postgres
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - perl -cw ./conf2sql.pl
  - perl -cw ./sql2conf.pl
  - git clone https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_conf_sql/
  - cp *.[ch] proftpd/contrib/mod_conf_sql/
  - cp *.pl proftpd/contrib/mod_conf_sql/
  - cp mod_conf_sql.* proftpd/contrib/mod_conf_sql/
  - cp Makefile.in proftpd/contrib/mod_conf_sql/
  - cp config* proftpd/contrib/mod_conf_sql/
  - cp install-sh proftpd/contrib/mod_conf_sql/
  - cp -R t/ proftpd/contrib/mod_conf_sql/t/
  - cp *.sql proftpd/contrib/mod_conf_sql/t/
  - cd proftpd
  - ./configure --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_sql:mod_conf_sql
  - make
  - make clean
  - ./configure --enable-devel=coverage --enable-tests --with-modules=mod_sql:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_conf_sql
  - make
  - cd contrib/mod_conf_sql && make TEST_VERBOSE=1 check && cd ../../
