# Example MySQL schema
CREATE TABLE ftpctxt IF NOT EXISTS (
  id INTEGER UNSIGNED UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  parent_id INTEGER UNSIGNED,
  name VARCHAR(255),
  type VARCHAR(255),
  info VARCHAR(255)
);

CREATE TABLE ftpconf IF NOT EXISTS (
  id INTEGER UNSIGNED UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  type VARCHAR(255) NOT NULL,
  info BLOB
);

CREATE TABLE ftpmap IF NOT EXISTS (
  conf_id INTEGER UNSIGNED NOT NULL,
  ctxt_id INTEGER UNSIGNED NOT NULL
);

