# Example SQLite schema

CREATE TABLE IF NOT EXISTS ftpctx (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent_id INTEGER UNSIGNED,
  name TEXT,
  key TEXT,
  value TEXT
);

CREATE TABLE IF NOT EXISTS ftpconf (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL,
  value BLOB
);

CREATE TABLE IF NOT EXISTS ftpmap (
  conf_id INTEGER UNSIGNED NOT NULL,
  ctx_id INTEGER UNSIGNED NOT NULL
);
