CREATE DATABASE IF NOT EXISTS proftpd;
USE proftpd;

CREATE TABLE IF NOT EXISTS ftpctx (
  id INTEGER UNSIGNED UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  parent_id INTEGER UNSIGNED,
  name VARCHAR(255),
  type VARCHAR(255),
  value VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ftpconf (
  id INTEGER UNSIGNED UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  value BLOB
);

CREATE TABLE IF NOT EXISTS ftpmap (
  conf_id INTEGER UNSIGNED NOT NULL,
  ctx_id INTEGER UNSIGNED NOT NULL
);
